version: "3.9"
services:
  postgres-nest:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: localdev
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
